### ISSUE TITLE
add github actions to build and lint

### ISSUE THREAD

**Issue by benekoehler** [michaeleggers/Bayernstein#4]
@michaeleggers i probably need your help for the windows build. as far as i saw it we can choose the platform in the actions without problems :) 

- [ ] setup linting on pull request
- [ ] setup linux builds and save the artifacts
- [ ] setup windows builds and save the artifacts

**Comment by michaeleggers** [comment]
> [@michaeleggers](https://github.com/michaeleggers) i probably need your help for the windows build. as far as i saw it we can choose the platform in the actions without problems :)
> 
> * [ ]  setup linting on pull request[ ]  setup linux builds and save the artifacts[ ]  setup windows builds and save the artifacts

Sure! Thanks for the setup.
